name: HyperBian CI Build
on: [push, pull_request]

jobs:
  rpi-image:
    name: "Build HyperBian image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl bc

      # build image
      - name: Build HyperBian
        run: |
          git clone https://github.com/tihoangyeudau/HyperBian.git
          git clone https://github.com/tihoangyeudau/pi-gen.git
          touch ./pi-gen/stage3/SKIP ./pi-gen/stage4/SKIP ./pi-gen/stage4/SKIP_IMAGES
          touch ./pi-gen/stage5/SKIP ./pi-gen/stage5/SKIP_IMAGES
          cp -R ./HyperBian/stage-hyperbian pi-gen/stage-hyperbian
          cp ./HyperBian/config pi-gen/config && cd pi-gen
          export LC_ALL='C.UTF-8'
          export LANGUAGE='C.UTF-8'
          export MESSENGE='C.UTF-8'
          sudo ./build.sh
          sudo mv ./deploy/*.zip ./deploy/HyperBian.zip
          sudo chown -fR $(stat -c "%U:%G" .) ./deploy

